### ISSUE TITLE
Add Public buckets by grayhatwarfare

### ISSUE THREAD

**Issue by bcoles** [lockfale/OSINT-Framework#101]
```json
{
  "id": "<ID>",
  "name": "Public buckets",
  "type": "url",
  "url": "https://buckets.grayhatwarfare.com/"
},
```

**Comment by s0lray** [comment]
Mulling over where in the various categories your two suggestions would best fit. I definitely thing both should be added and I might throw them in somewhere, but curious on your thoughts as to where they best fit...

**Comment by s0lray** [comment]
Added it to Domain Name > Cloud Resources (new category)
