### ISSUE TITLE
Request to add DeHashed.com

### ISSUE THREAD

**Issue by OSint-Rookie** [lockfale/OSINT-Framework#105]
Can conduct “password” searches.
(Email Address) > (Breach Data) > (DeHashed)

```
{
  "id": "<ID>",
  "name": "DeHashed",
  "type": "url",
  "url": "https://dehashed.com/"
},


```

**Comment by s0lray** [comment]
Thanks so much for all of the suggestions! I'm so excited right now! Just pushed an update and added all of the sites from your issues.

**Comment by OSint-Rookie** [comment]
Hello,

I checked out your OSINTframework last week after not seeing it for a while.  

Awesome work man!!

Thank you for adding my suggestions. 

I had an idea for a framework like this a long time ago, but I lack the skills to create it. 

Thank you for your work in making it happen and allowing all of us to be part of it.

**Comment by s0lray** [comment]
Thanks you! Suggestions are what makes this site so much better so I really appreciate it!
