### ISSUE TITLE
Request to add Credit Freeze

### ISSUE THREAD

**Issue by OSint-Rookie** [lockfale/OSINT-Framework#111]
Credit Freezes are very important for privacy enthusiasts and for anyone interested in personal data control. This is different than the _“OptOut Credit Prescreen id:1066”_
(OpSec) > ( Privacy / Clean Up) > (Credit Freeze)

```
{
  "id": "<ID>",
  "name": "Credit Freeze",
  "type": "url",
  "url": "https://inteltechniques.com/blog/2018/09/28/complete-credit-freeze-tutorial-update/"
},
```

**Comment by s0lray** [comment]
Added. Thank you!
