### ISSUE TITLE
Add ID Ransomware

### ISSUE THREAD

**Issue by neildotwilliams** [lockfale/OSINT-Framework#115]
Hi, I couldn't see it (under malicious file analysis?) so may be worth adding:
https://id-ransomware.malwarehunterteam.com/
Upload a ransom note and/or sample encrypted file to identify the ransomware that has encrypted your data.

**Comment by s0lray** [comment]
Ooh, this is cool. Thanks for the suggestion. Added it to Malicious File Analysis > Search
