### ISSUE TITLE
osintframework not working

### ISSUE THREAD

**Issue by tappon-louis** [lockfale/OSINT-Framework#116]
Love this project, but it seems like something is down at the moment - I keep getting this error across different browsers, operating systems and networks.

<img width="437" alt="screen shot 2018-10-08 at 2 15 38 pm" src="https://user-images.githubusercontent.com/39476417/46591182-be6e2f80-cb04-11e8-9a0a-59367e1ee6bc.png">

**Comment by s0lray** [comment]
Thanks for the heads up. Apparently one of my updates earlier today broke it. Should be back up and running again.

**Comment by proxyblue** [comment]
Yep. Confirmed. Guess you can cancel my PR then. I'll have to become a contributor some other way :P
