### ISSUE TITLE
mail tracking

### ISSUE THREAD

**Issue by 678trwird** [lockfale/OSINT-Framework#131]
I use Bananatag and MailTrack for gmail to track emails. I didn't see those on your list.

**Comment by opabravo** [comment]
You can make a pull request https://github.com/lockfale/OSINT-Framework/edit/master/public/arf.json
, instead of creating issues

**Comment by s0lray** [comment]
Added bananatag but not mailtrack. MailTrack's site seems dead even though the plugin is still available.
