### ISSUE TITLE
ASafaWeb Has Reached End of Life

### ISSUE THREAD

**Issue by enderlh** [lockfale/OSINT-Framework#132]
The ASafaWeb resource, in Domain Name > Vulnerabilities > Scanners is no longer working.
[https://asafaweb.com/](url)

> Half a dozen and a bit years after kicking off as a free tool for analysing the security config of ASP.NET applications, ASafaWeb has now reached the end of its life. Read the EOL blog post for more on why, and for other tools that can help you securely configure your web apps.

**Comment by s0lray** [comment]
Removed. Thanks for the heads up.
