### ISSUE TITLE
How to remove this framework from my computer? 

### ISSUE THREAD

**Issue by DenLeo** [lockfale/OSINT-Framework#138]
How to remove this framework from my computer? I have already reinstalled the operating system. The framework is constantly running in the browser.

**Comment by DenLeo** [comment]
I found my problem. The problem of page synchronization https://osintframework.com/ with the extensionhttps://chrome.google.com/webstore/detail/eversync-sync-bookmarks-b/iohcojnlgnfbmjfjfkbhahhmppcggdog?hl=ru

**Comment by melvin2001** [comment]
Have you tried deleting system32

**Comment by melvin2001** [comment]
Have you tried deleting system32

**Comment by digital-shokunin** [comment]
![image](https://user-images.githubusercontent.com/913856/100305209-93f2c100-2f6e-11eb-8d09-41be5993eb6c.png)
