### ISSUE TITLE
Special marking for dorks

### ISSUE THREAD

**Issue by x1sn0tz** [lockfale/OSINT-Framework#17]
Hi, thanks for a great framework. 

I noticed, that in the list there are many dorks (google queries) and from the first view they are undistinguishable from all the other links. Just as enhancement I can propose marking the dorks with (d) as you currently do with tools (t)

**Comment by s0lray** [comment]
I like it.  I'll start working on it and add a legend or something.

**Comment by x1sn0tz** [comment]
Nice to hear :+1:

**Comment by s0lray** [comment]
Implemented the following marks across about 50% of the resources in the update tonight.

(T) - Indicates a link to a tool that must be installed and run locally
(D) - Google Dork
(U) - Indicates a link that requires the URL that contains the search term and must be edited manually
(R) - Requires registration

**Comment by s0lray** [comment]
Tweaked the legend slightly.  Should push an update tomorrow with the remaining changes.

(T) - Indicates a link to a tool that must be installed and run locally
(D) - Google Dork, for more information: <link>
(R) - Requires registration
(M) - Indicates a URL that contains the search term and the URL itself must be edited manually

**Comment by s0lray** [comment]
Pushed and completed tagging all the links.  Except for all the ones that I missed...
