### ISSUE TITLE
Adding a tip for the link

### ISSUE THREAD

**Issue by srhnz67** [lockfale/OSINT-Framework#18]
First off..awesome work doing this.  One of the simplest ways I've come across to organise a mass amount of resources into logical groupings.  So I'm a noob to JSON and SVG, but having a look at the code in arf.js and chatting with mr google:

  nodeEnter.append("svg:title")
    .text(function(d) {
      return d.tip;
    });

Then add a "tip" field to the JSON child item (in fact, adding "tip" to any item adds a mouseover tip) :
"id": "502",
            "name": "Namechk",
            "type": "url",
            "url": "https://namechk.com/",
        "tip": "This is the tool tip for Namechk\nThis is line 2 of my tip"
On mouseover, your tooltip pops up, giving additional info as written in the JSON source.

Just a thought?
Cheers.

**Comment by s0lray** [comment]
I like this.  I'll have to play with it a bit but this could be one option to add some of the additional content that I would like to eventually have included in these and for some of the items that WebBreached suggested as well.

**Comment by s0lray** [comment]
The code is included to do this, now I just need to add descriptions and figure out some good way to indicate when a link has a description or not.

**Comment by srhnz67** [comment]
Different color for the endpoint?

**Comment by s0lray** [comment]
Closing this because the functionality is implemented.  Will be adding more descriptions on new content and reviewing existing content over the next few updates.
