### ISSUE TITLE
Add OWASP Maryam

### ISSUE THREAD

**Issue by saeeddhqan** [lockfale/OSINT-Framework#187]
It's an open-source intelligence(OSINT) framework written in python.

**Comment by krispyking** [comment]
Hi there

I am looking for some team members to build an OSINT service for individuals to use to understand how their digital footprint is left online. 

If anyone has an interest in joint a team then please do let me know. 

Ideally looking for a developer to build and iterate. I have a prominent CISO and business team and am looking for development partners 

Chris ransford. 
SitRepTOOL 


This message has been badly composed, poorly autocorrected and sent from one of my many I-Devices

**Comment by saeeddhqan** [comment]
Contact me: saeed.dehghan@owasp.org

**Comment by s0lray** [comment]
Added, thanks!
