### ISSUE TITLE
Modification in Hosted Automated Analysis

### ISSUE THREAD

**Issue by D3fD3c0y** [lockfale/OSINT-Framework#192]
Hi,
Just want to advise about some tools listed that no longer exist and some that can be added.

In Malicious File Analysis > Hosted Automated Analysis:

No longer exist:
Malwr
MalwareViz
Eureka
Deepviz Sandbox
ThreatExpert Sandbox
Anlyz.io

New one to add:
Intezer Analyze Community Edition (https://analyze.intezer.com/#/)
Sandblast (https://threatpoint.checkpoint.com/ThreatPortal/emulation)
SNDBOX (https://app.sndbox.com/login)
ViCheck (https://www.vicheck.ca/)
MalwareConfig (https://malwareconfig.com/)
OPSWAT Metadefender (https://metadefender.opswat.com/#!/)
VxCube (http://vxcube.com/)
Jotti malware scanner (https://virusscan.jotti.org/en-US/scan-file)

**Comment by s0lray** [comment]
Removed and added what was still free. Thanks!
