### ISSUE TITLE
Suggestion to update list of tools for Office and PDFs

### ISSUE THREAD

**Issue by D3fD3c0y** [lockfale/OSINT-Framework#193]
Hi,
Just want to advise about some tools listed that no longer exist and some that can be added.

In Malicious File Analysis > Hosted Automated Analysis > PDFs:

No longer exist:
Wepawet

New one to add:
PDF Examiner (https://www.malwaretracker.com/pdf.php)

In Malicious File Analysis > Hosted Automated Analysis > Office :

No longer exist:
XecScan

New one to add:
Quicksand (http://quicksand.io/)
Cryptam (https://www.cryptam.com/)

**Comment by s0lray** [comment]
Removed / Added. Thanks.
