### ISSUE TITLE
Suggestions to update list of Threat Intelligence

### ISSUE THREAD

**Issue by D3fD3c0y** [lockfale/OSINT-Framework#194]
Hi,
Just want to advise about some tools listed that can be added.

In threat Intelligence:

New one to add:
C1fApp (https://www.c1fapp.com/cifapp/login/)
RiskIQ Community Edition (https://community.riskiq.com/login)
AlienVault Open Threat Exchange	(https://otx.alienvault.com/)
CriticalStack Intel Feed (https://intel.criticalstack.com/user/login)
ThreatConnect (https://app.threatconnect.com/login.xhtml)
FireHOL IPList (http://iplists.firehol.org/)
Onyphe (https://www.onyphe.io/)
Maltiverse (https://www.maltiverse.com/search)
Malpedia (https://malpedia.caad.fkie.fraunhofer.de/library)

**Comment by s0lray** [comment]
Added, thanks.
