### ISSUE TITLE
Add new category: Reporting

### ISSUE THREAD

**Issue by D3fD3c0y** [lockfale/OSINT-Framework#196]
Hi,
Just want to suggest to add a new category named Reporting as a way to help reporting malicious IP/URL or malware samples:

Reporting > URL/Domains/IPs > Submit to Vendors > Webform:
CheckPoint (https://urlcat.checkpoint.com/urlcat/main.htm)
Microsoft (https://www.microsoft.com/en-us/wdsi/support/report-unsafe-site-guest)
Symantec (https://sitereview.symantec.com/#/)
Google (malware) (https://safebrowsing.google.com/safebrowsing/report_badware/)
Google (phishing) (https://safebrowsing.google.com/safebrowsing/report_phish/?hl=en)
CrowdStrike/Hybrid-Analysis (https://www.hybrid-analysis.com/)
BitDefender (https://www.bitdefender.com/submit/)
Malwarebytes (https://forums.malwarebytes.com/forum/44-research-center/)
McAfee (https://www.trustedsource.org/?p=mcafee)
Eset (https://phishing.eset.com/report)
Fortinet (https://fortiguard.com/faq/wfratingsubmit)
Trend Micro (https://global.sitesafety.trendmicro.com/)
F-Secure (https://www.f-secure.com/en/business/support-and-downloads/submit-a-sample)
Palo Alto (https://urlfiltering.paloaltonetworks.com/)
ForcePoint (https://csi.forcepoint.com/)

Reporting > URL/Domains/IPs > Submit to Vendors > E-mail:
Fortinet (fgweb@fortinet.com)
McAfee (sites@mcafee.com)
Panda (urls@pandasecurity.com)
Eset (samples@eset.com)
Palo Alto (support@paloaltonetworks.com)
BitDefender (virus_submission@bitdefender.com)

Reporting > Malwares > Submit to Vendors > Webform:
Fortinet (https://fortiguard.com/faq/onlinescanner)
GData (https://su.gdatasoftware.com/us/sample-submission/)
Malwarebytes (https://forums.malwarebytes.com/forum/44-research-center/)
F-Secure (https://www.f-secure.com/en/business/support-and-downloads/submit-a-sample)
Microsoft (https://www.microsoft.com/en-us/wdsi/filesubmission)

Reporting > Malwares > Submit to Vendors > E-mail:
Submit malware (zip file + pwd infected)
Avast (virus@avast.com)
Avira (virus@avira.com)
BitDefender (virus_submission@bitdefender.com)
Comodo (malwaresubmit@avlab.comodo.com)
DrWeb (vms@drweb.com)
Fortinet (submitvirus@fortinet.com)
F-Prot (viruslab@f-prot.com)
F-Secure (vsamples@f-secure.com)
Kaspersky (newvirus@kaspersky.com)
Microsoft (avsubmit@submit.microsoft.com)
Eset (samples@eset.com)
Panda (virus@pandasecurity.com)
Sophos (samples@sophos.com)
Symantec (avsubmit@symantec.com)
CheckPoint/ZOneAlarm malware@checkpoint.com
Vipre (malware-cruncher@sunbelt-software.com)

**Comment by s0lray** [comment]
Added some of the web reporting.
