### ISSUE TITLE
Application to automate searches

### ISSUE THREAD

**Issue by javixeneize** [lockfale/OSINT-Framework#205]
Hi

I’m thinking on building an application to automate the searches and results against all those sites listed in the framework using their exposed APIs when possible. I don’t know if anybody has started something like that yet but it might be a good community effort 

Would you be interested in taking part of that?

**Comment by krispyking** [comment]
I think that's a great idea can u email me on cransford at gmail dot com.

**Comment by R-Romanov** [comment]
@javixeneize Take a look at https://github.com/smicallef/spiderfoot
