### ISSUE TITLE
Suggestion: Reddit

### ISSUE THREAD

**Issue by cbraswe** [lockfale/OSINT-Framework#212]
Suggest adding a new website for Reddit, Reddit Metis: https://redditmetis.com/

It provides a significant amount of information concerning peak times, frequent words, and more. It is similar to Reddit Investigator, but it provides more visually based information.

I also suggest removing http://snoopsnoo.com/ since it gives a 404 error. Metareddit gives a domain for sale message.

**Comment by s0lray** [comment]
Added and removed suggestions. Thanks
