### ISSUE TITLE
Google Account Research Tool Ghunt

### ISSUE THREAD

**Issue by Spamfighter666** [lockfale/OSINT-Framework#224]
I suggest you add a link to this great tool https://github.com/mxrch/GHunt it can find these datapoints: 

- Owners Name
- YouTube Channel
- Other Usernames
- Maps Reviews
- Physical location
- Events from Google Cal
- Last time the profile was edited

it requires an email address, so perhaps it is best listed in that section of your tool

**Comment by s0lray** [comment]
Added, thanks.
