### ISSUE TITLE
List of various bad links and other issues encountered.

### ISSUE THREAD

**Issue by FoxinTale** [lockfale/OSINT-Framework#227]
Noticed multiple bad links that led nowhere, as well as a few other sites of note, and decided to begin making a list.
Others are welcome to comment any sites not listed that fall under the listed "categories", or if a site listed here is not agreed with. Open to corrections, feedback, and additions.

#### Websites which returned a 404 error:
  - Ark | https://ark.com/landing
  - Snoop Station | https://snoopstation.com/index.html
  - Speedy Hunt (Domain is for sale, also triggers uBlock Origin's blocking filters.) | https://speedyhunt.com/
  - TerraServer | https://www.terraserver.com/view
  - OnionTree | https://onionltd.github.io/
  - Gitleaks (Certificate expired, and leads to the domain being for sale) | https://gitleaks.com/
  - DMOZ (Not 404, 400, but close enough) | http://www.dmoz.org/
  - Carrot2 (Exists on archive.org, but unsure how reliable that one is) | http://search.carrot2.org/stable/search
  - Filemare (No 404, but domain is expired) | http://filemare.com/en-us
  - Economics Search Engine | http://ese.rfe.org/
  - SimilarSites (Also on archive.org, reliability unknown) | http://www.similarsites.com/browse
  - Google Correlate (Archive.org, reliability unknown) | https://www.google.com/trends/correlate/
  - The Investor - Africa (Returns a 401 error based off the little I understood) | http://theinvestormailinglist.com/recent-reports/
  - Mint Portal | http://mintbusinessinfo.com/version-2015129/portal.serv?product=mintportal
  - LeadFerret.com (Domain for sale) | https://leadferret.com/search
  - Enigma | https://enigma.com/publicdata
  

#### Websites which returned "DNS Probe Possible", but never loaded:  
  - Breach or Clear| http://breachorclear.jesterscourt.cc/ 
  - DNS Black Hole List (Ironically) | http://www.tcpiputils.com/dns-blackhole-list
  - eVerify | http://www.everify.com/
  - EntityCube | http://entitycube.research.microsoft.com/
  - Weleakinfo | https://search.weleakinfo.com/
  - Large -scale Scene Understanding challenge | http://lsun.cs.princeton.edu/2016/
  - Moose Roots Death Records | http://death-records.mooseroots.com/
  - Moose Roots Birth Records | http://birth-records.mooseroots.com/

#### Websites which return "CONNECTION_TIMED_OUT":
 - ProfileEngine | http://profileengine.com/
 - Additctomatic | http://addictomatic.com/
 - IceRocket | http://icerocket.com/
 - Yobi3D - 3D Model Search | https://www.yobi3d.com/#!/
 - Market Visual | http://www.marketvisual.com/

####  Websites which require payment to do anything, defeating the purpose of "freely available information":
 - Pipl | https://pipl.com/
 - Spokeo People Search | http://www.spokeo.com/
 - SearchBug | https://www.searchbug.com/#pageTop

#### Sites which require registration now (Not too huge of an issue, just need the little "R" appended to them):
 - Dehashed | https://dehashed.com/
 - Intelligence X (Shows short preview before requiring registration, and when registered, requires payment) | https://intelx.io/
 - Twingly (Discontinued searching, and now require registration to use for a "trial") | https://www.twingly.com/search
 - Orbis Directory | https://orbisdirectory.bvdinfo.com/version-2016121/OrbisDirectory/Companies
 - D&B Company Search (Register for a "free trial") | http://www.dnb.com/
 - XING | https://www.xing.com/

#### Other
 - The New Ultimates (uBlock's blocking filters activate, and redirects a blank page)| http://www.newultimates.com/
 - SkypeGrab (Same as The New Ultimates) http://ww7.skypegrab.net/?z
 - Scanless (Is a tool for Python, shouldn't it have the "T" appended?) | https://github.com/vesche/scanless
 - Notey (Is now a website builder instead of a search engine)  | https://www.notey.com/
 - Report Linker ("request a demo" only) | https://www.reportlinker.com/
 - BotBot.me (Unsure of this one, but the original service doesn't seem to be there.)  | https://botbot.me/
 - Yippy (Went straight to my default search engine) | http://yippy.com/
 - MediaBugs (Returns a 500 error, but also on archive.org) | http://mediabugs.org/

**Comment by Papadope** [comment]
Nice. Really great work, I hope someone sees that & change the links.

**Comment by rpmm24** [comment]
should have asked #272 to be added here

**Comment by r0ysen** [comment]
ProfileEngine work

**Comment by s0lray** [comment]
Amazing work. I should have caught this sooner. Updated and removed the entire list.
