### ISSUE TITLE
New tool: publicpolicerecord.com

### ISSUE THREAD

**Issue by otuva** [lockfale/OSINT-Framework#230]
This site is one of the best sites I've ever used. 

Pros:
You can search by name, race, gender, or/and location. 

Cons:
Only searches USA nationwide.

As far as I tested, site is pretty decent. Perhaps you can consider adding it. 

https://www.publicpolicerecord.com/

**Comment by willkeffer3** [comment]
So far, i don't see it as useful for past records.

**Comment by ThisRemindsMe** [comment]
Agreed, I searched for 3 different people's past arrests using very
specific information and couldn't get the search to land.
