### ISSUE TITLE
Tweet Analytic Sites which might need to be removed

### ISSUE THREAD

**Issue by kmarinaccio** [lockfale/OSINT-Framework#250]
The following websites are no longer working:
Social Networks > Twitter > Analytics > Profile:

- [ ] First Tweet (routes to about.twitter.com)
- [ ] Fake Follower Checker (DNS error, cannot resolve )
- [ ] TweetTunnel (re-routes to generic sketchy domain name webpage which happens when no one owns the domain)
- [ ] Twitalyzer (ERR_CONNECTION_TIMED_OUT)

**Comment by s0lray** [comment]
Removed in the next push. Thanks!
