### ISSUE TITLE
Addition of PassiveTotal to the list

### ISSUE THREAD

**Issue by 9b** [lockfale/OSINT-Framework#26]
I am one of the co-founders of PassiveTotal, now owned by RiskIQ. Our platform is a great resource for passive DNS, WHOIS, SSL certificates, web crawling and more. RiskIQ focuses on surfacing digital risk by web crawlers and Internet scanning. The PassiveTotal platform is a great way to pivot through the data sets to identify reputation, context and correlate OSINT. Registration is free and all accounts have enough queries to be useful on a daily basis.

**Comment by s0lray** [comment]
Oooh! My first vendor!  I feel like there should be a dinner invite or at least a beer included in here somewhere....  =)

PassiveTotal is already part of the framework under Domain > Reputation.  If you think it fits better under a different category, let me know.

**Comment by 9b** [comment]
You send me a link or an email and I will happily send over a couple 🍻 .

In regards to our listing, we are one of those special snowflake services that provides a lot of searching functionality. We have domain and IP reputation, but also our own OSINT collection, WHOIS searching and SSL certificate repository. I can email with you on some of the other data sets and get you access to them.

**Comment by glerinsonum** [comment]
@s0lray Hello Man. How I can integrating or executing these programming scripts into Maltego CE. Cordially thank you for good understanding.
