### ISSUE TITLE
Python server error

### ISSUE THREAD

**Issue by jmau111** [lockfale/OSINT-Framework#270]
hello,

it seems the script `npm start` does not work in some conditions:

> /usr/bin/python: No module named SimpleHTTPServer

The solution is to replace it with : `python3 -m http.server 8000`

**Comment by JamesClarke7283** [comment]
This issue is not resolved.

https://github.com/lockfale/OSINT-Framework/blob/c9655017bb8c56dc43664618b0b58a224865fccb/package.json#L8
