### ISSUE TITLE
Dead domain (siezed by fbi)

### ISSUE THREAD

**Issue by rpmm24** [lockfale/OSINT-Framework#272]
![image](https://user-images.githubusercontent.com/64339630/171069431-bd946895-41a9-4f6c-a6b1-84904cc8f70d.png)
The images say it all the domain is dead and not useful anymore  opsec>anon browse>anon vpns>https://www.deepdotweb.com/vpn-comparison-chart/

**Comment by thesaderror** [comment]
> ![image](https://user-images.githubusercontent.com/64339630/171069431-bd946895-41a9-4f6c-a6b1-84904cc8f70d.png) The images say it all the domain is dead and not useful anymore opsec>anon browse>anon vpns>https://www.deepdotweb.com/vpn-comparison-chart/

Hey if you need dark web links :
[darkweblink.com](https://www.similarweb.com/website/darkweblink.com/)
[thehiddenwiki.org](https://www.similarweb.com/website/thehiddenwiki.org/)
[thehackernews.com](https://www.similarweb.com/website/thehackernews.com/)
[deeponionweb.com](https://www.similarweb.com/website/deeponionweb.com/)
These are nice...
And if this comment is helpfull please mark it as answear. Thanks.

**Comment by s0lray** [comment]
Removed, thank you.
