### ISSUE TITLE
Addition of Wordreference to "Language Translation -> Text"

### ISSUE THREAD

**Issue by vtwarrior25** [lockfale/OSINT-Framework#276]
WordReference is a good resource for translating between languages. I have no personal affiliation with the service, I just like using the site for when I want to learn some more Spanish or something that I read in Spanish. The main advantage that it has over other services is the fact that it provides all of the possible meanings of the word in the target language, allowing you to take the context into account effectively.
The site is located at this link: [](https://www.wordreference.com/)

**Comment by r0ysen** [comment]
where link?

**Comment by vtwarrior25** [comment]
https://www.wordreference.com/

**Comment by s0lray** [comment]
Added in next push. Thanks!
