### ISSUE TITLE
email verification request for a better one

### ISSUE THREAD

**Issue by Daniel3356** [lockfale/OSINT-Framework#287]
Hi for inside the tab email address > email validation. I request to add [somorr.com](https://www.somorr.com/) email verifications. From my experience it's validate email differently without sending a test email address like the one [on the liste](https://osintframework.com/). 

By not sending any email to the user (broken smtp handshake) you stay more protected and less anonymous.

Best

**Comment by Michalzerah** [comment]
Hey daniel,
how i can use this website [somorr.com](https://www.somorr.com/) to do email validation?
thanks :)
