### ISSUE TITLE
Questionable Recomendations

### ISSUE THREAD

**Issue by JASory** [lockfale/OSINT-Framework#314]
Taking a brief survey over the "resources" enumerated in the source code, some issues keep emerging. Many of these provide no additional capability over an internet search, and possibly even more of them are primarily ads for their own service. 

One particularly unusual selection is the Epic browser. Chromium is open-source, Firefox is open-source , you can do anything with Chromium and Firefox that Epic browser claims (TOR uses Firefox and it has much stronger standards, and it too is [open-source](https://gitlab.torproject.org/tpo/applications/tor-browser)). So why is Epic so [evasive](https://forum.epicbrowser.com/viewtopic.php?id=636) when it comes to [publishing](https://www.epicbrowser.com/FAQ.html) it's source code?

That's only one example. This entire list should be reevaluated.

**Comment by Sud0nym4315** [comment]
I think this falls outside the scope of the goal of this tool. None of the tools have to be secure or private to fulfill the goal of performing passive reconnaissance.

**Comment by JASory** [comment]
Except it's primarily advertising. Anyone with some technical proficiency knows that these don't provide any unique capability. I cited the Epic browser as an egregious example as it is 1. obscure 2. Everything it claims is done better and in a verifiable way by much more notable browsers. 

"None of these have to be secure or private to fulfill the goal of passive reconnaissance"
There is nothing passive about connecting to a website. In fact traceability is a common concern in the OSINT community, as subjects that can trace users can cut-off information access. 

The critique here is that it is just a list of various websites and softwares, with no curation or evaluation of whether or not they are actually useful. Many of which are apparently useless, or even security risks.

**Comment by s0lray** [comment]
It's a valid critique, made worse by the difficultly in keeping a few thousand sites up to date with busy schedules. I removed the Epic browser from the list and if you have other sites you believe need to be reevaluated, please let us know.
