### ISSUE TITLE
Consider adding new tools - Hudson Rock free cybercrime intelligence tools

### ISSUE THREAD

**Issue by underthebreach** [lockfale/OSINT-Framework#327]
Hey, submitting the following tools to be added to OSINT-Framework:

Free cybercrime intelligence tools we built from over 13,000,000 computers that were compromised by info-stealers.

Our tools don't require registrations and include -

- Search for Compromised Corporate & Supply Chain Infrastructure (Discover whether your, or your vendor’s corporate infrastructure has been compromised)

- Search for Compromised Employees, Customers, Users & Partners (Search specific email
 addresses to find out if your employees, customers, users or partners have been compromised by info-stealing malware)

- Search for Compromised Android App Users (Find out whether users of your Android app have had their credentials compromised)

- Technology Profiler to Discover which Companies are Using a Technology

- Discover the Password Hygiene used in any company, search any domain to discover if password complexity requirements are implemented

They are all available here - https://www.hudsonrock.com/free-tools
Password hygiene available here - https://cavalier.hudsonrock.com/passwords
I would really appreciate it if you include us!

**Comment by s0lray** [comment]
Added, thanks!
