### ISSUE TITLE
Pishing Website in the list

### ISSUE THREAD

**Issue by Nextinor** [lockfale/OSINT-Framework#328]
![image](https://github.com/lockfale/OSINT-Framework/assets/116445739/eb3924eb-6015-4327-874e-3b0d3a3bd2ad)

Warning actually the link beside the red arrow is a pishing server redirecting here : 
Warning Don't click ! this is a pishing server !!
https://urchin-app-2-4baot.ondigitalocean.app/
Press esc for a will to exit full screen.

**Comment by s0lray** [comment]
Removed, thank you.
