### ISSUE TITLE
Eam Watch

### ISSUE THREAD

**Issue by KushagraKarira** [lockfale/OSINT-Framework#342]
Do we have this in database ? Cannot find on a code search.
https://eam.watch/

**Comment by QWERTAL124** [comment]
Yes it's account still available : https://t.co/OgQAyeMgrD

вс, 15 окт. 2023 г. в 12:32, KushagraKarira ***@***.***>:

**Comment by QWERTAL124** [comment]
What does it ?


ср, 25 окт. 2023 г. в 15:36, QWERTAL QWERTAL1 <
***@***.***>:

**Comment by QWERTAL124** [comment]
Living location  Yorkent ***@***.***,77.2480002

ср, 25 окт. 2023 г. в 15:36, QWERTAL QWERTAL1 <
***@***.***>:

**Comment by QWERTAL124** [comment]
Who do you work for ?

ср, 25 окт. 2023 г. в 15:42, QWERTAL QWERTAL1 <
***@***.***>:

**Comment by QWERTAL124** [comment]
Ajoyib! It's certainly important for me and arf.json


вс, 29 окт. 2023 г. в 20:36, KushagraKarira ***@***.***>:

**Comment by KushagraKarira** [comment]
>> Unable to understand anything after the second message.
What i am understanding is the other person is from RU.

My initial aim was to confirm if the eam.watch website was available on the website. Its certainly not something meant for people to just decode ( the codes seem to be in sets of 3 from left to right with each set being reference key with datetime ) but is an interesting OSINT website.

**Comment by QWERTAL124** [comment]
Great!

Yak, 29-okt, 2023, 8:36 TK KushagraKarira ***@***.***>:
