### ISSUE TITLE
Add the names of more websites under 'Dating' section

### ISSUE THREAD

**Issue by Nishant-Sagar** [lockfale/OSINT-Framework#347]
I was going through the framework and saw a lot of popular dating websites are missing inside the Dating section.
We can add websites like Bumble, Hinge and others as these are widely used platform.

**Comment by Nishant-Sagar** [comment]
Hi Team, Please assign this issue to me. I'll take this.

**Comment by QWERTAL124** [comment]
Can you describe me more information about your issue

**Comment by QWERTAL124** [comment]
With code section or image
