### ISSUE TITLE
Change privacytools.io to privacyguides.org

### ISSUE THREAD

**Issue by Imrealybored** [lockfale/OSINT-Framework#377]
Under OpSec > Privacy / Clean Up
privacytools.io has been filled with sponsored recommendations to less private apps and services. 

privacyguides.org is a much better site that keeps it simple and doesn't push sponsored content.

**Comment by s0lray** [comment]
Privacyguides looks great. Added that to the top of the list. Keeping privacytools for the moment until I have time to review. It didn't look super aggressive with the sponsors on a 2 second glance but I need to check closer.
