### ISSUE TITLE
Is this repo dead ?

### ISSUE THREAD

**Issue by lynnwilliam** [lockfale/OSINT-Framework#384]
I've seen no updates in 9 months and some of the links mentioned are dead.

**Comment by 404ram** [comment]
If you check the closed PRs there are a bunch of them that are 3 weeks old

**Comment by melvin2001** [comment]
we're just not very good at our job.

**Comment by s0lray** [comment]
What @melvin2001 said. Lots more updates recently, but also work and vacations are a thing.

**Comment by EmailScraper** [comment]
?
