### ISSUE TITLE
lower level requirements missing

### ISSUE THREAD

**Issue by nealrauhauser** [lockfale/OSINT-Framework#40]
I'm installing this in a Lubuntu VM I use for forensics. I am not a regular user of node/npm/bower.

First, it wasn't clear that node needed to be installed, maybe say more about prerequisites for someone starting from scratch?

Then this happened:

./node_modules/bower/bin/bower install
bower                     invalid-meta for:/home/hunch/OSINT-Framework/bower.json
bower                     invalid-meta The "name" is recommended to be lowercase, can contain digits, dots, dashes

https://github.com/lockfale/ARF redirects to https://github.com/lockfale/OSINT-Framework, not sure if that's a problem, I manually fixed it in bower.json. After this I read bower help, check, and this is installed.

./node_modules/bower/bin/bower list
bower check-new     Checking for new versions of the project dependencies...
arf /home/hunch/OSINT-Framework
└── d3#3.5.16 (latest is 4.7.1)

Executive Summary - this app could stand a careful documenting from start to finish on a fresh Ubuntu system not used by a knowledgeable JavaScript person.

**Comment by treefort** [comment]
hey @nealrauhauser, thanks for the issue! I'll be updating the README shortly to include better instructions on how to get this up and running in a wider variety of environments.
