### ISSUE TITLE
Add HoneyDB + CLI.

### ISSUE THREAD

**Issue by NullArray** [lockfale/OSINT-Framework#44]
Hello, i would like to make a suggestion with regards to a resource and a tool to be added to OSINT-Framework. The resource i am referring to is [HoneyDB](https://riskdiscovery.com/honeydb/about). Which in short is an aggregative threat intel pool. HoneyDB collects and organizes data on malicious hosts from HoneyPy honeypots. They offer a threat feed and provide data visualization services as well.

Secondly i am the author of a command line interface which makes it easier for security researchers to retrieve and process the data provided by HoneyDB. The CLI saves logs of the malicious hosts and allows the user to perform an in-script WHOIS lookup and invoke an Nmap scan as well in order to learn more about a particular target if and when desired.

The name of the CLI i wrote is Mimir and you can find it in it's repo on my Github page.

https://github.com/NullArray/Mimir

With kind regards, 
NullArray.

**Comment by Chan9390** [comment]
Hey @NullArray is your tool stable now ?

**Comment by NullArray** [comment]
Hi @Chan9390 it is stable yes. Everything seems to be in order, and i have added some logic to have my it check the user's version of PycURL and rebuild it automatically to support OpenSSL in the event that the user's version does not.

All SSL issues are resolved.

**Comment by s0lray** [comment]
Added now, thanks guys!
