### ISSUE TITLE
Addition Belati to the list

### ISSUE THREAD

**Issue by aancw** [lockfale/OSINT-Framework#47]
Hi, I'm the author of Belati( https://github.com/aancw/Belati )

```
Belati - The Traditional Swiss Army Knife For OSINT

Belati is tool for Collecting Public Data & Public Document from Website and other service for OSINT purpose. This tools is inspired by Foca and Datasploit for OSINT :)
```

I want to make pull request, but i don't know what number should i use for id. 195 is already used by folder:

```
{
            "id": "195",
            "name": "Belati (T)",
            "type": "url",
            "url": "https://github.com/aancw/Belati"
         }],
```

Thanks!

**Comment by mrpnkt** [comment]
I don't know how IDs are assigned, but i suggest to use the next free ID (which is 1109). that's how i have added links. great tool btw!

**Comment by aancw** [comment]
I think id is incremental, but if that's ok to use next free ID then i will submit pull request.

Thanks! Still on development progress and many TODO-list :)

**Comment by s0lray** [comment]
Awesome!  Thanks for the suggestion and PR!  I just downloaded Belati to play with it as well!
