### ISSUE TITLE
HTTP Server

### ISSUE THREAD

**Issue by pierlon** [lockfale/OSINT-Framework#56]
Why use python as the HTTP server when [http-server](https://www.npmjs.com/package/http-server) could be used instead? One less dependency.

**Comment by treefort** [comment]
@pierlon: I'm not crazy about `-g` installs unless absolutely necessary. in this case, python is not a dependency, per se—the `npm start` script is provided for convenience as most people running this repo locally will likely have python already installed. that said, definitely feel free to use the http server of choice. I'm a fan of [http-server](https://www.npmjs.com/package/http-server) myself. :)

**Comment by treefort** [comment]
closing unless @s0lray wants to shake things up in the local server department.

**Comment by pierlon** [comment]
Oh OK. I created a [docker image](https://hub.docker.com/r/pierlo1/osint-framework/) so python wasn't needed in that case.

**Comment by treefort** [comment]
dude, nice. do you mind if we include a link to your docker image in the README?

**Comment by pierlon** [comment]
Sure, no problem.
