### ISSUE TITLE
Use of python is not obvious, particularly python version

### ISSUE THREAD

**Issue by Structed** [lockfale/OSINT-Framework#57]
The README.md only casually mentions the use of python. The very brief statement actually assumes the use of python 2, because the used `SimpleHTTPServer` module was merged to the python core with python 3 and is now called `http.server`.

Apart from this documentation need, the dependency on python is probably superfluous, because a webserver could also be hosted with node itself (but that's for another issue).

**Comment by treefort** [comment]
as this application runs entirely in the client, it does not depend on python. any static http server will work just fine. that isn't clear in the README, so I'll update accordingly. :D

**Comment by ElectricCaffeine** [comment]
I'm stuck trying to get this tool moving. I cloned, but i have a handful of JSON files now. I can't do bower install.

please help

Thanks
EC

**Comment by treefort** [comment]
hey @ElectricCaffeine, everything you need is in `/public`. to get this working, open the repo directory in a terminal, then...
if you have python v2.x, run: `cd ./public; python -m SimpleHTTPServer 8000`
if you have python v3.x, run: `cd ./public; python -m http.server 8000`

**Comment by ElectricCaffeine** [comment]
Thanks for the quick response! I'm in the web menu now. @treefort

**Comment by treefort** [comment]
awesome! :D

**Comment by ElectricCaffeine** [comment]
forgive my ignorance, but once I got it running once, I just created a bookmark of http://localhost:8000. I won't need to launch Simple HTTP server anymore, right?

**Comment by treefort** [comment]
so long as that python process is running, you will be able to access http://localhost:8000. if you reboot or anything, you'll need to run that command again. basically, all that command is doing is spinning up a tiny web server for the static files in the `/public` directory.

**Comment by ElectricCaffeine** [comment]
oh ok..thanks for the explanation. I started exploring some of the tree branches, looks like all external websites right?

**Comment by treefort** [comment]
yep :)

**Comment by NullArray** [comment]
Hey @ElectricCaffeine! Not sure which distro you are running but i am on Ubuntu and an easy way to start the SimpleHTTPServer automatically for me is to just make a small shell script in my home directory. Like so;

```
touch o-start.sh
chmod + x o-start.sh
```
Then open `o-start.sh` with your favourite text editor and paste the following lines.

```
#!/bin/bash

echo -e "\n\x1b[32;01m[+]Starting server at 127.0.0.1:8000\x1b[39;49;00m"
sleep 2

cd "/path/to/your/OSINT-Framework"
npm start
```
Where you of course replace `/path/to/OSINT-Framework` with your directory. Something like `/home/ElectricCaffeine/OSINT-Framework`. Then lastly you just make a simple symbolic link to your `o-start.sh` script in your `/etc/profile.d/`directory. Like so:

`sudo ln -s /home/ElectricCaffeine/o-start.sh /etc/profile.d/o-start.sh` 

This will make it so the SimpleHTTPServer runs automatically every time you log in. All that's left to do is click on the bookmark you made for the page and you're set. Good luck!

**Comment by 0x69676f72** [comment]
Finally worked. 
```
C:\Users\IgorMonteiroVieira\Desktop\OSINT-Framework>python
Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:14:34) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
KeyboardInterrupt
>>> ^Z


C:\Users\IgorMonteiroVieira\Desktop\OSINT-Framework>cd public

C:\Users\IgorMonteiroVieira\Desktop\OSINT-Framework\public>python -m http.server 8000
Serving HTTP on 0.0.0.0 port 8000 (http://0.0.0.0:8000/) ...
```
