### ISSUE TITLE
Document ID assignment

### ISSUE THREAD

**Issue by Structed** [lockfale/OSINT-Framework#59]
For contributors, it is not obvious how to assign an ID to a `folder` or `url` node (or any other, if there are any, for that matter).

Also, it is perhaps a good idea to use GUIDs for the ID fields to have non-conflicting UIDs when creating pull requests.

**Comment by treefort** [comment]
thanks for the feedback, @Structed! it's not particularly clear how to contribute at this point; I'll chat with @s0lray about how to best update the README.

**Comment by Structed** [comment]
I'd like to add a new entry, how would I choose an ID at this very moment? Just find an unused, low number?

**Comment by treefort** [comment]
it looks like the ID is just the next lowest unused integer. I don't want to spin your wheels though... could @mrpnkt or @s0lray confirm?

**Comment by mrpnkt** [comment]
Yes. I choose the next lowest integer when adding a new link.

**Comment by s0lray** [comment]
Mulling over some ideas on this...  I have one that I might put in for the short term, but it isn't great...

**Comment by bcoles** [comment]
It's not easy to contribute to this project, as everything is bundled in the `arf.json` file.

This effectively guarantees constant merge conflicts.

**Comment by s0lray** [comment]
Closing this for now. Similar to ID #78 and a short term solution has been implemented. Added a description field to the root OSINT framework folder that lists the next available ID.
