### ISSUE TITLE
Add WhatWeb (T)

### ISSUE THREAD

**Issue by bcoles** [lockfale/OSINT-Framework#72]
WhatWeb - Web application and web server fingerprinting tool.

*Domain Name -> Analytics:*

```json
            {
              "id": "<ID>",
              "name": "WhatWeb (T)",
              "type": "url",
              "url": "https://github.com/urbanadventurer/WhatWeb"
},
```

**Comment by s0lray** [comment]
Awesome project, going to have to spin this up and play with it!

Added to the recommended category.
