### ISSUE TITLE
Description of resource

### ISSUE THREAD

**Issue by WebBreacher** [lockfale/OSINT-Framework#8]
Wondering what your thoughts on adding a brief description of the resource so people know what that link will give them. 

Other things to possibly add to the JSON might be:
1. Description (described above)
2. Cost or free ($ for paid, 0 for free)
3. Requires registration (pick an icon/symbol for this) yes or no
4. Reliability Ranking - Is the resource solid or false positive-prone?
5. Usefulness Ranking - Of all the resources in the category, which are the ones that someone should visit first to get the most bang for their time?

Just some ideas on extending your useful project.

**Comment by s0lray** [comment]
Yes!  Most of these things are on the to do list, which I should probably publish as well.  Still parsing through about 1k more tools/links and then I'm going to start working this direction.  Couple of other thoughts...
Originally my intention was to only add tools that were either free or at least offer a free trial.  So far this applies to everything but the training I believe.  Reliability/Usefulness ranking is going to be hard without crowdsourcing this to some degree, but I would like to get there.  Also had some ideas around a chrome extension that would allow for accepting some of that input easier, but that is way farther off in the future.

**Comment by s0lray** [comment]
Closing this since the functionality is built in now.  Adding descriptions for more new links / tools that are getting added.  Just need to go back and catch up on the existing ones over time.
