### ISSUE TITLE
some rf stuff

### ISSUE THREAD

**Issue by al1ce23** [lockfale/OSINT-Framework#83]
https://github.com/eldraco/Salamandra
https://github.com/xmikos/qspectrumanalyzer
https://github.com/ghostop14/sparrow-wifi
https://github.com/Oros42/IMSI-catcher

more https://github.com/cn0xroot/RFSec-ToolKit

**Comment by al1ce23** [comment]
ping sms android app https://github.com/itds-consulting/android-silent-ping-sms

**Comment by mrpnkt** [comment]
I checked and those are all tools, not really OSINT sources. Although some are quite awesome I wouldn't add them to the osintframework.

**Comment by s0lray** [comment]
Agreed with @mrpnkt. Going to close this without adding them for now.
