### ISSUE TITLE
Conversion script

### ISSUE THREAD

**Issue by 304GEEK** [lockfale/OSINT-Framework#89]
JN,
Just curious what you are generating your arf.json from. are you converting from .mm or some other standard? interested in sharing the script, if so?

doesn't hurt to ask I hope :)

Thanks,

**Comment by s0lray** [comment]
Oh man I'm sorry I missed this for so long. No fancy secret sauce here. There is probably a lot ways that would be a lot more efficient and I'm always open to ideas / suggestions. I originally started generating the json from a Chrome bookmark backup file. It had a lot of additional fields that I had to strip out. At this point I'm usually not making massive changes so I'm just editing it manually.
